<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFramework>netstandard2.1</TargetFramework>
        <ImplicitUsings>disable</ImplicitUsings>
        <OutputType>library</OutputType>
        <GeneratePackageOnBuild>True</GeneratePackageOnBuild>
        <Title>Simple Communication Models.</Title>
        <Version>0.0.2</Version>
        <Description>A simple .NET Standard 2.1 class library with reusable data models for communication.</Description>
        <RepositoryUrl>https://github.com/a-t-k/</RepositoryUrl>
        <PackageLicenseFile>LICENSE</PackageLicenseFile>
        <PackageReadmeFile>README.md</PackageReadmeFile>
        <IncludeContentInPack>true</IncludeContentInPack>
    </PropertyGroup>

    <ItemGroup>
        <None Include="LICENSE">
            <Pack>true</Pack>
            <PackagePath></PackagePath>
            <Visible>True</Visible>
        </None>
        <None Include="README.md">
            <Pack>true</Pack>
            <PackagePath></PackagePath>
            <Visible>True</Visible>
        </None>
    </ItemGroup>
</Project>
