<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <OutputType>library</OutputType>
        <GeneratePackageOnBuild>True</GeneratePackageOnBuild>
        <Title>Simple WebCommunicationModels.</Title>
        <Version>0.0.1</Version>
        <Description>A simple .NET Standard 2.1 class library with reusable data models for web communication.</Description>
        <RepositoryUrl>https://github.com/a-t-k/WebCommunicationModels/</RepositoryUrl>
        <PackageLicenseFile>LICENSE</PackageLicenseFile>
        <PackageReadmeFile>README.md</PackageReadmeFile>
        <IncludeContentInPack>true</IncludeContentInPack>
    </PropertyGroup>

    <ItemGroup>
        <None Include="LICENSE">
            <Pack>true</Pack>
            <PackagePath></PackagePath>
            <Visible>True</Visible>
        </None>
        <None Include="README.md">
            <Pack>true</Pack>
            <PackagePath></PackagePath>
            <Visible>True</Visible>
        </None>
    </ItemGroup>
</Project>
